{{- if .Values.configs.segment_backup_job.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: segment-backup-job
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - get
  - list
- apiGroups:
  - "route.openshift.io"
  resources:
  - routes
  verbs:
  - get
  - list 
- apiGroups:
  - "operator.openshift.io/v1"
  resources:
  - console
  verbs:
  - get
{{- end}}
